// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/collab_messages.proto

package edu.caltech.cs141b.hw5.data;

public final class CollabMessages {
	private CollabMessages() {}
	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}
	public enum StatusType
	implements com.google.protobuf.Internal.EnumLite {
		SUCCESS(0, 0),
		UNKNOWN_ERROR(1, 1),
		INVALID_REQUEST(2, 2),
		LOCK_UNAVAILABLE(3, 3),
		LOCK_EXPIRED(4, 4),
		;

		public static final int SUCCESS_VALUE = 0;
		public static final int UNKNOWN_ERROR_VALUE = 1;
		public static final int INVALID_REQUEST_VALUE = 2;
		public static final int LOCK_UNAVAILABLE_VALUE = 3;
		public static final int LOCK_EXPIRED_VALUE = 4;


		public final int getNumber() { return value; }

		public static StatusType valueOf(int value) {
			switch (value) {
			case 0: return SUCCESS;
			case 1: return UNKNOWN_ERROR;
			case 2: return INVALID_REQUEST;
			case 3: return LOCK_UNAVAILABLE;
			case 4: return LOCK_EXPIRED;
			default: return null;
			}
		}

		public static com.google.protobuf.Internal.EnumLiteMap<StatusType>
		internalGetValueMap() {
			return internalValueMap;
		}
		private static com.google.protobuf.Internal.EnumLiteMap<StatusType>
		internalValueMap =
		new com.google.protobuf.Internal.EnumLiteMap<StatusType>() {
			public StatusType findValueByNumber(int number) {
				return StatusType.valueOf(number);
			}
		};

		private final int value;

		private StatusType(int index, int value) {
			this.value = value;
		}

		// @@protoc_insertion_point(enum_scope:cs141b.StatusType)
	}

	public enum RequestType
	implements com.google.protobuf.Internal.EnumLite {
		GET_DOCUMENT_LIST(0, 0),
		LOCK_DOCUMENT(1, 1),
		GET_DOCUMENT(2, 2),
		SAVE_DOCUMENT(3, 3),
		RELEASE_LOCK(4, 4),
		;

		public static final int GET_DOCUMENT_LIST_VALUE = 0;
		public static final int LOCK_DOCUMENT_VALUE = 1;
		public static final int GET_DOCUMENT_VALUE = 2;
		public static final int SAVE_DOCUMENT_VALUE = 3;
		public static final int RELEASE_LOCK_VALUE = 4;


		public final int getNumber() { return value; }

		public static RequestType valueOf(int value) {
			switch (value) {
			case 0: return GET_DOCUMENT_LIST;
			case 1: return LOCK_DOCUMENT;
			case 2: return GET_DOCUMENT;
			case 3: return SAVE_DOCUMENT;
			case 4: return RELEASE_LOCK;
			default: return null;
			}
		}

		public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
		internalGetValueMap() {
			return internalValueMap;
		}
		private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
		internalValueMap =
		new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
			public RequestType findValueByNumber(int number) {
				return RequestType.valueOf(number);
			}
		};

		private final int value;

		private RequestType(int index, int value) {
			this.value = value;
		}

		// @@protoc_insertion_point(enum_scope:cs141b.RequestType)
	}

	public interface DocumentMetaInfoOrBuilder
	extends com.google.protobuf.MessageLiteOrBuilder {

		// required string key = 1;
		boolean hasKey();
		String getKey();

		// required string title = 2;
		boolean hasTitle();
		String getTitle();
	}
	public static final class DocumentMetaInfo extends
	com.google.protobuf.GeneratedMessageLite
	implements DocumentMetaInfoOrBuilder {
		// Use DocumentMetaInfo.newBuilder() to construct.
		private DocumentMetaInfo(Builder builder) {
			super(builder);
		}
		private DocumentMetaInfo(boolean noInit) {}

		private static final DocumentMetaInfo defaultInstance;
		public static DocumentMetaInfo getDefaultInstance() {
			return defaultInstance;
		}

		public DocumentMetaInfo getDefaultInstanceForType() {
			return defaultInstance;
		}

		private int bitField0_;
		// required string key = 1;
		public static final int KEY_FIELD_NUMBER = 1;
		private java.lang.Object key_;
		public boolean hasKey() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		public String getKey() {
			java.lang.Object ref = key_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					key_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getKeyBytes() {
			java.lang.Object ref = key_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				key_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string title = 2;
		public static final int TITLE_FIELD_NUMBER = 2;
		private java.lang.Object title_;
		public boolean hasTitle() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		public String getTitle() {
			java.lang.Object ref = title_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					title_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getTitleBytes() {
			java.lang.Object ref = title_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				title_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			key_ = "";
			title_ = "";
		}
		private byte memoizedIsInitialized = -1;
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasKey()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasTitle()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getKeyBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getTitleBytes());
			}
		}

		private int memoizedSerializedSize = -1;
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getKeyBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(2, getTitleBytes());
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		public Builder toBuilder() { return newBuilder(this); }

		public static final class Builder extends
		com.google.protobuf.GeneratedMessageLite.Builder<
		edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo, Builder>
		implements edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfoOrBuilder {
			// Construct using edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}
			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				key_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				title_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo getDefaultInstanceForType() {
				return edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo.getDefaultInstance();
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo build() {
				edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo buildPartial() {
				edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo result = new edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.key_ = key_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.title_ = title_;
				result.bitField0_ = to_bitField0_;
				return result;
			}

			public Builder mergeFrom(edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo other) {
				if (other == edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo.getDefaultInstance()) return this;
				if (other.hasKey()) {
					setKey(other.getKey());
				}
				if (other.hasTitle()) {
					setTitle(other.getTitle());
				}
				return this;
			}

			public final boolean isInitialized() {
				if (!hasKey()) {

					return false;
				}
				if (!hasTitle()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:

						return this;
					default: {
						if (!parseUnknownField(input, extensionRegistry, tag)) {

							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						key_ = input.readBytes();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						title_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required string key = 1;
			private java.lang.Object key_ = "";
			public boolean hasKey() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			public String getKey() {
				java.lang.Object ref = key_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					key_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setKey(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				key_ = value;

				return this;
			}
			public Builder clearKey() {
				bitField0_ = (bitField0_ & ~0x00000001);
				key_ = getDefaultInstance().getKey();

				return this;
			}
			void setKey(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				key_ = value;

			}

			// required string title = 2;
			private java.lang.Object title_ = "";
			public boolean hasTitle() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			public String getTitle() {
				java.lang.Object ref = title_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					title_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setTitle(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				title_ = value;

				return this;
			}
			public Builder clearTitle() {
				bitField0_ = (bitField0_ & ~0x00000002);
				title_ = getDefaultInstance().getTitle();

				return this;
			}
			void setTitle(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				title_ = value;

			}

			// @@protoc_insertion_point(builder_scope:cs141b.DocumentMetaInfo)
		}

		static {
			defaultInstance = new DocumentMetaInfo(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:cs141b.DocumentMetaInfo)
	}

	public interface LockedDocumentInfoOrBuilder
	extends com.google.protobuf.MessageLiteOrBuilder {

		// optional string lockedBy = 1;
		boolean hasLockedBy();
		String getLockedBy();

		// optional int64 lockedUntil = 2;
		boolean hasLockedUntil();
		long getLockedUntil();

		// optional string key = 3;
		boolean hasKey();
		String getKey();

		// required string title = 4;
		boolean hasTitle();
		String getTitle();

		// required string contents = 5;
		boolean hasContents();
		String getContents();
	}
	public static final class LockedDocumentInfo extends
	com.google.protobuf.GeneratedMessageLite
	implements LockedDocumentInfoOrBuilder {
		// Use LockedDocumentInfo.newBuilder() to construct.
		private LockedDocumentInfo(Builder builder) {
			super(builder);
		}
		private LockedDocumentInfo(boolean noInit) {}

		private static final LockedDocumentInfo defaultInstance;
		public static LockedDocumentInfo getDefaultInstance() {
			return defaultInstance;
		}

		public LockedDocumentInfo getDefaultInstanceForType() {
			return defaultInstance;
		}

		private int bitField0_;
		// optional string lockedBy = 1;
		public static final int LOCKEDBY_FIELD_NUMBER = 1;
		private java.lang.Object lockedBy_;
		public boolean hasLockedBy() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		public String getLockedBy() {
			java.lang.Object ref = lockedBy_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					lockedBy_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getLockedByBytes() {
			java.lang.Object ref = lockedBy_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				lockedBy_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional int64 lockedUntil = 2;
		public static final int LOCKEDUNTIL_FIELD_NUMBER = 2;
		private long lockedUntil_;
		public boolean hasLockedUntil() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		public long getLockedUntil() {
			return lockedUntil_;
		}

		// optional string key = 3;
		public static final int KEY_FIELD_NUMBER = 3;
		private java.lang.Object key_;
		public boolean hasKey() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}
		public String getKey() {
			java.lang.Object ref = key_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					key_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getKeyBytes() {
			java.lang.Object ref = key_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				key_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string title = 4;
		public static final int TITLE_FIELD_NUMBER = 4;
		private java.lang.Object title_;
		public boolean hasTitle() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}
		public String getTitle() {
			java.lang.Object ref = title_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					title_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getTitleBytes() {
			java.lang.Object ref = title_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				title_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string contents = 5;
		public static final int CONTENTS_FIELD_NUMBER = 5;
		private java.lang.Object contents_;
		public boolean hasContents() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}
		public String getContents() {
			java.lang.Object ref = contents_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					contents_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getContentsBytes() {
			java.lang.Object ref = contents_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				contents_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			lockedBy_ = "";
			lockedUntil_ = 0L;
			key_ = "";
			title_ = "";
			contents_ = "";
		}
		private byte memoizedIsInitialized = -1;
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasTitle()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasContents()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getLockedByBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt64(2, lockedUntil_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getKeyBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBytes(4, getTitleBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(5, getContentsBytes());
			}
		}

		private int memoizedSerializedSize = -1;
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getLockedByBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeInt64Size(2, lockedUntil_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(3, getKeyBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(4, getTitleBytes());
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(5, getContentsBytes());
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		public Builder toBuilder() { return newBuilder(this); }

		public static final class Builder extends
		com.google.protobuf.GeneratedMessageLite.Builder<
		edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo, Builder>
		implements edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfoOrBuilder {
			// Construct using edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}
			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				lockedBy_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				lockedUntil_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000002);
				key_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				title_ = "";
				bitField0_ = (bitField0_ & ~0x00000008);
				contents_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo getDefaultInstanceForType() {
				return edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo build() {
				edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo buildPartial() {
				edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo result = new edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.lockedBy_ = lockedBy_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.lockedUntil_ = lockedUntil_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.key_ = key_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.title_ = title_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.contents_ = contents_;
				result.bitField0_ = to_bitField0_;
				return result;
			}

			public Builder mergeFrom(edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo other) {
				if (other == edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance()) return this;
				if (other.hasLockedBy()) {
					setLockedBy(other.getLockedBy());
				}
				if (other.hasLockedUntil()) {
					setLockedUntil(other.getLockedUntil());
				}
				if (other.hasKey()) {
					setKey(other.getKey());
				}
				if (other.hasTitle()) {
					setTitle(other.getTitle());
				}
				if (other.hasContents()) {
					setContents(other.getContents());
				}
				return this;
			}

			public final boolean isInitialized() {
				if (!hasTitle()) {

					return false;
				}
				if (!hasContents()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:

						return this;
					default: {
						if (!parseUnknownField(input, extensionRegistry, tag)) {

							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						lockedBy_ = input.readBytes();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						lockedUntil_ = input.readInt64();
						break;
					}
					case 26: {
						bitField0_ |= 0x00000004;
						key_ = input.readBytes();
						break;
					}
					case 34: {
						bitField0_ |= 0x00000008;
						title_ = input.readBytes();
						break;
					}
					case 42: {
						bitField0_ |= 0x00000010;
						contents_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// optional string lockedBy = 1;
			private java.lang.Object lockedBy_ = "";
			public boolean hasLockedBy() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			public String getLockedBy() {
				java.lang.Object ref = lockedBy_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					lockedBy_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setLockedBy(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				lockedBy_ = value;

				return this;
			}
			public Builder clearLockedBy() {
				bitField0_ = (bitField0_ & ~0x00000001);
				lockedBy_ = getDefaultInstance().getLockedBy();

				return this;
			}
			void setLockedBy(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				lockedBy_ = value;

			}

			// optional int64 lockedUntil = 2;
			private long lockedUntil_ ;
			public boolean hasLockedUntil() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			public long getLockedUntil() {
				return lockedUntil_;
			}
			public Builder setLockedUntil(long value) {
				bitField0_ |= 0x00000002;
				lockedUntil_ = value;

				return this;
			}
			public Builder clearLockedUntil() {
				bitField0_ = (bitField0_ & ~0x00000002);
				lockedUntil_ = 0L;

				return this;
			}

			// optional string key = 3;
			private java.lang.Object key_ = "";
			public boolean hasKey() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}
			public String getKey() {
				java.lang.Object ref = key_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					key_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setKey(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				key_ = value;

				return this;
			}
			public Builder clearKey() {
				bitField0_ = (bitField0_ & ~0x00000004);
				key_ = getDefaultInstance().getKey();

				return this;
			}
			void setKey(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000004;
				key_ = value;

			}

			// required string title = 4;
			private java.lang.Object title_ = "";
			public boolean hasTitle() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}
			public String getTitle() {
				java.lang.Object ref = title_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					title_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setTitle(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				title_ = value;

				return this;
			}
			public Builder clearTitle() {
				bitField0_ = (bitField0_ & ~0x00000008);
				title_ = getDefaultInstance().getTitle();

				return this;
			}
			void setTitle(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000008;
				title_ = value;

			}

			// required string contents = 5;
			private java.lang.Object contents_ = "";
			public boolean hasContents() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}
			public String getContents() {
				java.lang.Object ref = contents_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					contents_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setContents(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				contents_ = value;

				return this;
			}
			public Builder clearContents() {
				bitField0_ = (bitField0_ & ~0x00000010);
				contents_ = getDefaultInstance().getContents();

				return this;
			}
			void setContents(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000010;
				contents_ = value;

			}

			// @@protoc_insertion_point(builder_scope:cs141b.LockedDocumentInfo)
		}

		static {
			defaultInstance = new LockedDocumentInfo(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:cs141b.LockedDocumentInfo)
	}

	public interface UnlockedDocumentInfoOrBuilder
	extends com.google.protobuf.MessageLiteOrBuilder {

		// required string key = 1;
		boolean hasKey();
		String getKey();

		// required string title = 2;
		boolean hasTitle();
		String getTitle();

		// required string contents = 3;
		boolean hasContents();
		String getContents();
	}
	public static final class UnlockedDocumentInfo extends
	com.google.protobuf.GeneratedMessageLite
	implements UnlockedDocumentInfoOrBuilder {
		// Use UnlockedDocumentInfo.newBuilder() to construct.
		private UnlockedDocumentInfo(Builder builder) {
			super(builder);
		}
		private UnlockedDocumentInfo(boolean noInit) {}

		private static final UnlockedDocumentInfo defaultInstance;
		public static UnlockedDocumentInfo getDefaultInstance() {
			return defaultInstance;
		}

		public UnlockedDocumentInfo getDefaultInstanceForType() {
			return defaultInstance;
		}

		private int bitField0_;
		// required string key = 1;
		public static final int KEY_FIELD_NUMBER = 1;
		private java.lang.Object key_;
		public boolean hasKey() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		public String getKey() {
			java.lang.Object ref = key_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					key_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getKeyBytes() {
			java.lang.Object ref = key_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				key_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string title = 2;
		public static final int TITLE_FIELD_NUMBER = 2;
		private java.lang.Object title_;
		public boolean hasTitle() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		public String getTitle() {
			java.lang.Object ref = title_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					title_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getTitleBytes() {
			java.lang.Object ref = title_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				title_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string contents = 3;
		public static final int CONTENTS_FIELD_NUMBER = 3;
		private java.lang.Object contents_;
		public boolean hasContents() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}
		public String getContents() {
			java.lang.Object ref = contents_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					contents_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getContentsBytes() {
			java.lang.Object ref = contents_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				contents_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			key_ = "";
			title_ = "";
			contents_ = "";
		}
		private byte memoizedIsInitialized = -1;
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasKey()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasTitle()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasContents()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getKeyBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getTitleBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getContentsBytes());
			}
		}

		private int memoizedSerializedSize = -1;
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getKeyBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(2, getTitleBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(3, getContentsBytes());
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		public Builder toBuilder() { return newBuilder(this); }

		public static final class Builder extends
		com.google.protobuf.GeneratedMessageLite.Builder<
		edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo, Builder>
		implements edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfoOrBuilder {
			// Construct using edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}
			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				key_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				title_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				contents_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo getDefaultInstanceForType() {
				return edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance();
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo build() {
				edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo buildPartial() {
				edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo result = new edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.key_ = key_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.title_ = title_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.contents_ = contents_;
				result.bitField0_ = to_bitField0_;
				return result;
			}

			public Builder mergeFrom(edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo other) {
				if (other == edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance()) return this;
				if (other.hasKey()) {
					setKey(other.getKey());
				}
				if (other.hasTitle()) {
					setTitle(other.getTitle());
				}
				if (other.hasContents()) {
					setContents(other.getContents());
				}
				return this;
			}

			public final boolean isInitialized() {
				if (!hasKey()) {

					return false;
				}
				if (!hasTitle()) {

					return false;
				}
				if (!hasContents()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:

						return this;
					default: {
						if (!parseUnknownField(input, extensionRegistry, tag)) {

							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						key_ = input.readBytes();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						title_ = input.readBytes();
						break;
					}
					case 26: {
						bitField0_ |= 0x00000004;
						contents_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required string key = 1;
			private java.lang.Object key_ = "";
			public boolean hasKey() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			public String getKey() {
				java.lang.Object ref = key_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					key_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setKey(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				key_ = value;

				return this;
			}
			public Builder clearKey() {
				bitField0_ = (bitField0_ & ~0x00000001);
				key_ = getDefaultInstance().getKey();

				return this;
			}
			void setKey(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				key_ = value;

			}

			// required string title = 2;
			private java.lang.Object title_ = "";
			public boolean hasTitle() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			public String getTitle() {
				java.lang.Object ref = title_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					title_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setTitle(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				title_ = value;

				return this;
			}
			public Builder clearTitle() {
				bitField0_ = (bitField0_ & ~0x00000002);
				title_ = getDefaultInstance().getTitle();

				return this;
			}
			void setTitle(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				title_ = value;

			}

			// required string contents = 3;
			private java.lang.Object contents_ = "";
			public boolean hasContents() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}
			public String getContents() {
				java.lang.Object ref = contents_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					contents_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setContents(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				contents_ = value;

				return this;
			}
			public Builder clearContents() {
				bitField0_ = (bitField0_ & ~0x00000004);
				contents_ = getDefaultInstance().getContents();

				return this;
			}
			void setContents(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000004;
				contents_ = value;

			}

			// @@protoc_insertion_point(builder_scope:cs141b.UnlockedDocumentInfo)
		}

		static {
			defaultInstance = new UnlockedDocumentInfo(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:cs141b.UnlockedDocumentInfo)
	}

	public interface RequestMessageOrBuilder
	extends com.google.protobuf.MessageLiteOrBuilder {

		// required .cs141b.RequestType requestType = 1;
		boolean hasRequestType();
		edu.caltech.cs141b.hw5.data.CollabMessages.RequestType getRequestType();

		// optional string documentKey = 2;
		boolean hasDocumentKey();
		String getDocumentKey();

		// optional .cs141b.LockedDocumentInfo lockedDoc = 3;
		boolean hasLockedDoc();
		edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo getLockedDoc();
	}
	public static final class RequestMessage extends
	com.google.protobuf.GeneratedMessageLite
	implements RequestMessageOrBuilder {
		// Use RequestMessage.newBuilder() to construct.
		private RequestMessage(Builder builder) {
			super(builder);
		}
		private RequestMessage(boolean noInit) {}

		private static final RequestMessage defaultInstance;
		public static RequestMessage getDefaultInstance() {
			return defaultInstance;
		}

		public RequestMessage getDefaultInstanceForType() {
			return defaultInstance;
		}

		private int bitField0_;
		// required .cs141b.RequestType requestType = 1;
		public static final int REQUESTTYPE_FIELD_NUMBER = 1;
		private edu.caltech.cs141b.hw5.data.CollabMessages.RequestType requestType_;
		public boolean hasRequestType() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		public edu.caltech.cs141b.hw5.data.CollabMessages.RequestType getRequestType() {
			return requestType_;
		}

		// optional string documentKey = 2;
		public static final int DOCUMENTKEY_FIELD_NUMBER = 2;
		private java.lang.Object documentKey_;
		public boolean hasDocumentKey() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		public String getDocumentKey() {
			java.lang.Object ref = documentKey_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					documentKey_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getDocumentKeyBytes() {
			java.lang.Object ref = documentKey_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				documentKey_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional .cs141b.LockedDocumentInfo lockedDoc = 3;
		public static final int LOCKEDDOC_FIELD_NUMBER = 3;
		private edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo lockedDoc_;
		public boolean hasLockedDoc() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}
		public edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo getLockedDoc() {
			return lockedDoc_;
		}

		private void initFields() {
			requestType_ = edu.caltech.cs141b.hw5.data.CollabMessages.RequestType.GET_DOCUMENT_LIST;
			documentKey_ = "";
			lockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
		}
		private byte memoizedIsInitialized = -1;
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasRequestType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (hasLockedDoc()) {
				if (!getLockedDoc().isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeEnum(1, requestType_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getDocumentKeyBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeMessage(3, lockedDoc_);
			}
		}

		private int memoizedSerializedSize = -1;
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeEnumSize(1, requestType_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(2, getDocumentKeyBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(3, lockedDoc_);
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		public Builder toBuilder() { return newBuilder(this); }

		public static final class Builder extends
		com.google.protobuf.GeneratedMessageLite.Builder<
		edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage, Builder>
		implements edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessageOrBuilder {
			// Construct using edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}
			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				requestType_ = edu.caltech.cs141b.hw5.data.CollabMessages.RequestType.GET_DOCUMENT_LIST;
				bitField0_ = (bitField0_ & ~0x00000001);
				documentKey_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				lockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage getDefaultInstanceForType() {
				return edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage.getDefaultInstance();
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage build() {
				edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage buildPartial() {
				edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage result = new edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.requestType_ = requestType_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.documentKey_ = documentKey_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.lockedDoc_ = lockedDoc_;
				result.bitField0_ = to_bitField0_;
				return result;
			}

			public Builder mergeFrom(edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage other) {
				if (other == edu.caltech.cs141b.hw5.data.CollabMessages.RequestMessage.getDefaultInstance()) return this;
				if (other.hasRequestType()) {
					setRequestType(other.getRequestType());
				}
				if (other.hasDocumentKey()) {
					setDocumentKey(other.getDocumentKey());
				}
				if (other.hasLockedDoc()) {
					mergeLockedDoc(other.getLockedDoc());
				}
				return this;
			}

			public final boolean isInitialized() {
				if (!hasRequestType()) {

					return false;
				}
				if (hasLockedDoc()) {
					if (!getLockedDoc().isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:

						return this;
					default: {
						if (!parseUnknownField(input, extensionRegistry, tag)) {

							return this;
						}
						break;
					}
					case 8: {
						int rawValue = input.readEnum();
						edu.caltech.cs141b.hw5.data.CollabMessages.RequestType value = edu.caltech.cs141b.hw5.data.CollabMessages.RequestType.valueOf(rawValue);
						if (value != null) {
							bitField0_ |= 0x00000001;
							requestType_ = value;
						}
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						documentKey_ = input.readBytes();
						break;
					}
					case 26: {
						edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.Builder subBuilder = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.newBuilder();
						if (hasLockedDoc()) {
							subBuilder.mergeFrom(getLockedDoc());
						}
						input.readMessage(subBuilder, extensionRegistry);
						setLockedDoc(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required .cs141b.RequestType requestType = 1;
			private edu.caltech.cs141b.hw5.data.CollabMessages.RequestType requestType_ = edu.caltech.cs141b.hw5.data.CollabMessages.RequestType.GET_DOCUMENT_LIST;
			public boolean hasRequestType() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			public edu.caltech.cs141b.hw5.data.CollabMessages.RequestType getRequestType() {
				return requestType_;
			}
			public Builder setRequestType(edu.caltech.cs141b.hw5.data.CollabMessages.RequestType value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				requestType_ = value;

				return this;
			}
			public Builder clearRequestType() {
				bitField0_ = (bitField0_ & ~0x00000001);
				requestType_ = edu.caltech.cs141b.hw5.data.CollabMessages.RequestType.GET_DOCUMENT_LIST;

				return this;
			}

			// optional string documentKey = 2;
			private java.lang.Object documentKey_ = "";
			public boolean hasDocumentKey() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			public String getDocumentKey() {
				java.lang.Object ref = documentKey_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					documentKey_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setDocumentKey(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				documentKey_ = value;

				return this;
			}
			public Builder clearDocumentKey() {
				bitField0_ = (bitField0_ & ~0x00000002);
				documentKey_ = getDefaultInstance().getDocumentKey();

				return this;
			}
			void setDocumentKey(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				documentKey_ = value;

			}

			// optional .cs141b.LockedDocumentInfo lockedDoc = 3;
			private edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo lockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
			public boolean hasLockedDoc() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}
			public edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo getLockedDoc() {
				return lockedDoc_;
			}
			public Builder setLockedDoc(edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo value) {
				if (value == null) {
					throw new NullPointerException();
				}
				lockedDoc_ = value;

				bitField0_ |= 0x00000004;
				return this;
			}
			public Builder setLockedDoc(
					edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.Builder builderForValue) {
				lockedDoc_ = builderForValue.build();

				bitField0_ |= 0x00000004;
				return this;
			}
			public Builder mergeLockedDoc(edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo value) {
				if (((bitField0_ & 0x00000004) == 0x00000004) &&
						lockedDoc_ != edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance()) {
					lockedDoc_ =
							edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.newBuilder(lockedDoc_).mergeFrom(value).buildPartial();
				} else {
					lockedDoc_ = value;
				}

				bitField0_ |= 0x00000004;
				return this;
			}
			public Builder clearLockedDoc() {
				lockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();

				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			// @@protoc_insertion_point(builder_scope:cs141b.RequestMessage)
		}

		static {
			defaultInstance = new RequestMessage(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:cs141b.RequestMessage)
	}

	public interface ResponseMessageOrBuilder
	extends com.google.protobuf.MessageLiteOrBuilder {

		// required .cs141b.StatusType statusType = 1;
		boolean hasStatusType();
		edu.caltech.cs141b.hw5.data.CollabMessages.StatusType getStatusType();

		// optional string message = 2;
		boolean hasMessage();
		String getMessage();

		// repeated .cs141b.DocumentMetaInfo docMeta = 3;
		java.util.List<edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo> 
		getDocMetaList();
		edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo getDocMeta(int index);
		int getDocMetaCount();

		// optional .cs141b.LockedDocumentInfo lockedDoc = 4;
		boolean hasLockedDoc();
		edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo getLockedDoc();

		// optional .cs141b.UnlockedDocumentInfo unlockedDoc = 5;
		boolean hasUnlockedDoc();
		edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo getUnlockedDoc();
	}
	public static final class ResponseMessage extends
	com.google.protobuf.GeneratedMessageLite
	implements ResponseMessageOrBuilder {
		// Use ResponseMessage.newBuilder() to construct.
		private ResponseMessage(Builder builder) {
			super(builder);
		}
		private ResponseMessage(boolean noInit) {}

		private static final ResponseMessage defaultInstance;
		public static ResponseMessage getDefaultInstance() {
			return defaultInstance;
		}

		public ResponseMessage getDefaultInstanceForType() {
			return defaultInstance;
		}

		private int bitField0_;
		// required .cs141b.StatusType statusType = 1;
		public static final int STATUSTYPE_FIELD_NUMBER = 1;
		private edu.caltech.cs141b.hw5.data.CollabMessages.StatusType statusType_;
		public boolean hasStatusType() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		public edu.caltech.cs141b.hw5.data.CollabMessages.StatusType getStatusType() {
			return statusType_;
		}

		// optional string message = 2;
		public static final int MESSAGE_FIELD_NUMBER = 2;
		private java.lang.Object message_;
		public boolean hasMessage() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		public String getMessage() {
			java.lang.Object ref = message_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = 
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					message_ = s;
				}
				return s;
			}
		}
		private com.google.protobuf.ByteString getMessageBytes() {
			java.lang.Object ref = message_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = 
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				message_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// repeated .cs141b.DocumentMetaInfo docMeta = 3;
		public static final int DOCMETA_FIELD_NUMBER = 3;
		private java.util.List<edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo> docMeta_;
		public java.util.List<edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo> getDocMetaList() {
			return docMeta_;
		}
		public java.util.List<? extends edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfoOrBuilder> 
		getDocMetaOrBuilderList() {
			return docMeta_;
		}
		public int getDocMetaCount() {
			return docMeta_.size();
		}
		public edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo getDocMeta(int index) {
			return docMeta_.get(index);
		}
		public edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfoOrBuilder getDocMetaOrBuilder(
				int index) {
			return docMeta_.get(index);
		}

		// optional .cs141b.LockedDocumentInfo lockedDoc = 4;
		public static final int LOCKEDDOC_FIELD_NUMBER = 4;
		private edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo lockedDoc_;
		public boolean hasLockedDoc() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}
		public edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo getLockedDoc() {
			return lockedDoc_;
		}

		// optional .cs141b.UnlockedDocumentInfo unlockedDoc = 5;
		public static final int UNLOCKEDDOC_FIELD_NUMBER = 5;
		private edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo unlockedDoc_;
		public boolean hasUnlockedDoc() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}
		public edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo getUnlockedDoc() {
			return unlockedDoc_;
		}

		private void initFields() {
			statusType_ = edu.caltech.cs141b.hw5.data.CollabMessages.StatusType.SUCCESS;
			message_ = "";
			docMeta_ = java.util.Collections.emptyList();
			lockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
			unlockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance();
		}
		private byte memoizedIsInitialized = -1;
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			if (!hasStatusType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getDocMetaCount(); i++) {
				if (!getDocMeta(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			if (hasLockedDoc()) {
				if (!getLockedDoc().isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			if (hasUnlockedDoc()) {
				if (!getUnlockedDoc().isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeEnum(1, statusType_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getMessageBytes());
			}
			for (int i = 0; i < docMeta_.size(); i++) {
				output.writeMessage(3, docMeta_.get(i));
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeMessage(4, lockedDoc_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeMessage(5, unlockedDoc_);
			}
		}

		private int memoizedSerializedSize = -1;
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeEnumSize(1, statusType_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(2, getMessageBytes());
			}
			for (int i = 0; i < docMeta_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(3, docMeta_.get(i));
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(4, lockedDoc_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(5, unlockedDoc_);
			}
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;
		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseFrom(
				com.google.protobuf.ByteString data)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseFrom(
				com.google.protobuf.CodedInputStream input)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		public static edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() { return Builder.create(); }
		public Builder newBuilderForType() { return newBuilder(); }
		public static Builder newBuilder(edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		public Builder toBuilder() { return newBuilder(this); }

		public static final class Builder extends
		com.google.protobuf.GeneratedMessageLite.Builder<
		edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage, Builder>
		implements edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessageOrBuilder {
			// Construct using edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
			}
			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				statusType_ = edu.caltech.cs141b.hw5.data.CollabMessages.StatusType.SUCCESS;
				bitField0_ = (bitField0_ & ~0x00000001);
				message_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				docMeta_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000004);
				lockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
				bitField0_ = (bitField0_ & ~0x00000008);
				unlockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance();
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage getDefaultInstanceForType() {
				return edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage.getDefaultInstance();
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage build() {
				edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			public edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage buildPartial() {
				edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage result = new edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.statusType_ = statusType_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.message_ = message_;
				if (((bitField0_ & 0x00000004) == 0x00000004)) {
					docMeta_ = java.util.Collections.unmodifiableList(docMeta_);
					bitField0_ = (bitField0_ & ~0x00000004);
				}
				result.docMeta_ = docMeta_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000004;
				}
				result.lockedDoc_ = lockedDoc_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000008;
				}
				result.unlockedDoc_ = unlockedDoc_;
				result.bitField0_ = to_bitField0_;
				return result;
			}

			public Builder mergeFrom(edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage other) {
				if (other == edu.caltech.cs141b.hw5.data.CollabMessages.ResponseMessage.getDefaultInstance()) return this;
				if (other.hasStatusType()) {
					setStatusType(other.getStatusType());
				}
				if (other.hasMessage()) {
					setMessage(other.getMessage());
				}
				if (!other.docMeta_.isEmpty()) {
					if (docMeta_.isEmpty()) {
						docMeta_ = other.docMeta_;
						bitField0_ = (bitField0_ & ~0x00000004);
					} else {
						ensureDocMetaIsMutable();
						docMeta_.addAll(other.docMeta_);
					}

				}
				if (other.hasLockedDoc()) {
					mergeLockedDoc(other.getLockedDoc());
				}
				if (other.hasUnlockedDoc()) {
					mergeUnlockedDoc(other.getUnlockedDoc());
				}
				return this;
			}

			public final boolean isInitialized() {
				if (!hasStatusType()) {

					return false;
				}
				for (int i = 0; i < getDocMetaCount(); i++) {
					if (!getDocMeta(i).isInitialized()) {

						return false;
					}
				}
				if (hasLockedDoc()) {
					if (!getLockedDoc().isInitialized()) {

						return false;
					}
				}
				if (hasUnlockedDoc()) {
					if (!getUnlockedDoc().isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:

						return this;
					default: {
						if (!parseUnknownField(input, extensionRegistry, tag)) {

							return this;
						}
						break;
					}
					case 8: {
						int rawValue = input.readEnum();
						edu.caltech.cs141b.hw5.data.CollabMessages.StatusType value = edu.caltech.cs141b.hw5.data.CollabMessages.StatusType.valueOf(rawValue);
						if (value != null) {
							bitField0_ |= 0x00000001;
							statusType_ = value;
						}
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						message_ = input.readBytes();
						break;
					}
					case 26: {
						edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo.Builder subBuilder = edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addDocMeta(subBuilder.buildPartial());
						break;
					}
					case 34: {
						edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.Builder subBuilder = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.newBuilder();
						if (hasLockedDoc()) {
							subBuilder.mergeFrom(getLockedDoc());
						}
						input.readMessage(subBuilder, extensionRegistry);
						setLockedDoc(subBuilder.buildPartial());
						break;
					}
					case 42: {
						edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.Builder subBuilder = edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.newBuilder();
						if (hasUnlockedDoc()) {
							subBuilder.mergeFrom(getUnlockedDoc());
						}
						input.readMessage(subBuilder, extensionRegistry);
						setUnlockedDoc(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required .cs141b.StatusType statusType = 1;
			private edu.caltech.cs141b.hw5.data.CollabMessages.StatusType statusType_ = edu.caltech.cs141b.hw5.data.CollabMessages.StatusType.SUCCESS;
			public boolean hasStatusType() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			public edu.caltech.cs141b.hw5.data.CollabMessages.StatusType getStatusType() {
				return statusType_;
			}
			public Builder setStatusType(edu.caltech.cs141b.hw5.data.CollabMessages.StatusType value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				statusType_ = value;

				return this;
			}
			public Builder clearStatusType() {
				bitField0_ = (bitField0_ & ~0x00000001);
				statusType_ = edu.caltech.cs141b.hw5.data.CollabMessages.StatusType.SUCCESS;

				return this;
			}

			// optional string message = 2;
			private java.lang.Object message_ = "";
			public boolean hasMessage() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			public String getMessage() {
				java.lang.Object ref = message_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					message_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			public Builder setMessage(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				message_ = value;

				return this;
			}
			public Builder clearMessage() {
				bitField0_ = (bitField0_ & ~0x00000002);
				message_ = getDefaultInstance().getMessage();

				return this;
			}
			void setMessage(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				message_ = value;

			}

			// repeated .cs141b.DocumentMetaInfo docMeta = 3;
			private java.util.List<edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo> docMeta_ =
					java.util.Collections.emptyList();
			private void ensureDocMetaIsMutable() {
				if (!((bitField0_ & 0x00000004) == 0x00000004)) {
					docMeta_ = new java.util.ArrayList<edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo>(docMeta_);
					bitField0_ |= 0x00000004;
				}
			}

			public java.util.List<edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo> getDocMetaList() {
				return java.util.Collections.unmodifiableList(docMeta_);
			}
			public int getDocMetaCount() {
				return docMeta_.size();
			}
			public edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo getDocMeta(int index) {
				return docMeta_.get(index);
			}
			public Builder setDocMeta(
					int index, edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureDocMetaIsMutable();
				docMeta_.set(index, value);

				return this;
			}
			public Builder setDocMeta(
					int index, edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo.Builder builderForValue) {
				ensureDocMetaIsMutable();
				docMeta_.set(index, builderForValue.build());

				return this;
			}
			public Builder addDocMeta(edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureDocMetaIsMutable();
				docMeta_.add(value);

				return this;
			}
			public Builder addDocMeta(
					int index, edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureDocMetaIsMutable();
				docMeta_.add(index, value);

				return this;
			}
			public Builder addDocMeta(
					edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo.Builder builderForValue) {
				ensureDocMetaIsMutable();
				docMeta_.add(builderForValue.build());

				return this;
			}
			public Builder addDocMeta(
					int index, edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo.Builder builderForValue) {
				ensureDocMetaIsMutable();
				docMeta_.add(index, builderForValue.build());

				return this;
			}
			public Builder addAllDocMeta(
					java.lang.Iterable<? extends edu.caltech.cs141b.hw5.data.CollabMessages.DocumentMetaInfo> values) {
				ensureDocMetaIsMutable();
				super.addAll(values, docMeta_);

				return this;
			}
			public Builder clearDocMeta() {
				docMeta_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000004);

				return this;
			}
			public Builder removeDocMeta(int index) {
				ensureDocMetaIsMutable();
				docMeta_.remove(index);

				return this;
			}

			// optional .cs141b.LockedDocumentInfo lockedDoc = 4;
			private edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo lockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();
			public boolean hasLockedDoc() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}
			public edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo getLockedDoc() {
				return lockedDoc_;
			}
			public Builder setLockedDoc(edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo value) {
				if (value == null) {
					throw new NullPointerException();
				}
				lockedDoc_ = value;

				bitField0_ |= 0x00000008;
				return this;
			}
			public Builder setLockedDoc(
					edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.Builder builderForValue) {
				lockedDoc_ = builderForValue.build();

				bitField0_ |= 0x00000008;
				return this;
			}
			public Builder mergeLockedDoc(edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo value) {
				if (((bitField0_ & 0x00000008) == 0x00000008) &&
						lockedDoc_ != edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance()) {
					lockedDoc_ =
							edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.newBuilder(lockedDoc_).mergeFrom(value).buildPartial();
				} else {
					lockedDoc_ = value;
				}

				bitField0_ |= 0x00000008;
				return this;
			}
			public Builder clearLockedDoc() {
				lockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.LockedDocumentInfo.getDefaultInstance();

				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			// optional .cs141b.UnlockedDocumentInfo unlockedDoc = 5;
			private edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo unlockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance();
			public boolean hasUnlockedDoc() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}
			public edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo getUnlockedDoc() {
				return unlockedDoc_;
			}
			public Builder setUnlockedDoc(edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo value) {
				if (value == null) {
					throw new NullPointerException();
				}
				unlockedDoc_ = value;

				bitField0_ |= 0x00000010;
				return this;
			}
			public Builder setUnlockedDoc(
					edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.Builder builderForValue) {
				unlockedDoc_ = builderForValue.build();

				bitField0_ |= 0x00000010;
				return this;
			}
			public Builder mergeUnlockedDoc(edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo value) {
				if (((bitField0_ & 0x00000010) == 0x00000010) &&
						unlockedDoc_ != edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance()) {
					unlockedDoc_ =
							edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.newBuilder(unlockedDoc_).mergeFrom(value).buildPartial();
				} else {
					unlockedDoc_ = value;
				}

				bitField0_ |= 0x00000010;
				return this;
			}
			public Builder clearUnlockedDoc() {
				unlockedDoc_ = edu.caltech.cs141b.hw5.data.CollabMessages.UnlockedDocumentInfo.getDefaultInstance();

				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			// @@protoc_insertion_point(builder_scope:cs141b.ResponseMessage)
		}

		static {
			defaultInstance = new ResponseMessage(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:cs141b.ResponseMessage)
	}


	static {
	}

	// @@protoc_insertion_point(outer_class_scope)
}
